/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_opencv_androidstudio_opencv_readpicture_MainActivity */

#ifndef _Included_com_android_opencv_androidstudio_opencv_readpicture_MainActivity
#define _Included_com_android_opencv_androidstudio_opencv_readpicture_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_opencv_androidstudio_opencv_readpicture_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_opencv_androidstudio_1opencv_1readpicture_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_android_opencv_androidstudio_opencv_readpicture_MainActivity
 * Method:    imageProcessJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_opencv_androidstudio_1opencv_1readpicture_MainActivity_imageProcessJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_android_opencv_androidstudio_opencv_readpicture_MainActivity
 * Method:    imageProcessGrayJNI
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_android_opencv_androidstudio_1opencv_1readpicture_MainActivity_imageProcessGrayJNI
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
